name: Question
description: How do I...?
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: What are you trying to do?
    validations:
      required: true
  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
